name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 9.3.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'


      - name: Inject Git Commit
        run: |
          sed -i "s/val gitCommit = \"unknown\"/val gitCommit = \"${GITHUB_SHA::7}\"/" app/build.gradle.kts
      - name: Build debug APK
        run: gradle assembleDebug --stacktrace


      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/OBDLogger-v1.0.0-build100-debug.apk || true
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: KylaqOBD2Scan-debug-apk
          path: app/build/outputs/apk/debug/*.apk
